### ISSUE TITLE
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#101]
```
Panic at 2015-03-07T18:03:42+01:00
panic: interface conversion: *iterator.emptyIterator is not iterator.ErrorCallbackSetter: missing method SetErrorCallback

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.func·010(0x7f197f0fd210, 0xc2080fe440, 0x0, 0x0)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:355 +0x5f7
github.com/syndtr/goleveldb/leveldb.recoverTable(0xc2080c00b0, 0xc2080be140, 0x0, 0x0)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:430 +0x677
github.com/syndtr/goleveldb/leveldb.Recover(0x7f197f0fd010, 0xc208100120, 0xc2080be280, 0x0, 0x0, 0x0)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:227 +0x128
github.com/syndtr/goleveldb/leveldb.RecoverFile(0xc2080f6a20, 0x24, 0xc2080be280, 0x0, 0x0, 0x0)
    /go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:249 +0x98
main.syncthingMain()
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:499 +0x146e
main.main()
    /go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:368 +0x20ed
```

Panic as above when doing RecoverFile on a database that failed the normal open. Obviously the db is corrupt somehow (not sure, this is at another user), but the panic seems unrelated to the actual corruption?

**Comment by calmh** [comment]
(leveldb 63c9e642efad852f49e20a6f90194cae112fd2ac)

**Comment by syndtr** [comment]
Yes, it's not related to the corruption. I should use "comma ok" in there.
