### ISSUE TITLE
panic: unexpected fault address 0x0

### ISSUE THREAD

**Issue by karalabe** [syndtr/goleveldb#115]
We had a user report regular crashes in our code (https://github.com/ethereum/go-ethereum/issues/1437), and it seems that they originate from the leveldb compactor. Any ideas?

PS: We have a vendored copy of leveldb. Maybe it's an older bug that has been fixed since? https://github.com/ethereum/go-ethereum/blob/develop/Godeps/Godeps.json#L91

````
unexpected fault address 0x0
fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x850f88]
 
goroutine 72 [running]:
runtime.gothrow(0xd47e90, 0x5)
	/usr/lib/go/src/runtime/panic.go:503 +0x8e fp=0xc21d893260 sp=0xc21d893248
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc21d8932b0 sp=0xc21d893260
github.com/syndtr/goleveldb/leveldb/iterator.(*indexedIterator).Key(0xc2082648a0, 0x0, 0x9f968a, 0xc217b8fae0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/iterator/indexed_iter.go:198 +0x28 fp=0xc21d8932e8 sp=0xc21d8932b0
github.com/syndtr/goleveldb/leveldb/iterator.(*mergedIterator).Next(0xc20bfd4500, 0xc216f108d0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/iterator/merged_iter.go:170 +0x33c fp=0xc21d8933d8 sp=0xc21d8932e8
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc20bee80a0, 0xc21ba32468, 0x0, 0x0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:455 +0x483 fp=0xc21d8935a0 sp=0xc21d8933d8
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc2081c82c0, 0xd98930, 0xb, 0x7f246a7718b0, 0xc20bee80a0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215 +0x277 fp=0xc21d893888 sp=0xc21d8935a0
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc2081c82c0, 0xc20a7fc400, 0x0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:596 +0x10d4 fp=0xc21d893c60 sp=0xc21d893888
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc2081c82c0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:641 +0x50 fp=0xc21d893c80 sp=0xc21d893c60
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2081c82c0)
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:833 +0x3a0 fp=0xc21d893fd8 sp=0xc21d893c80
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc21d893fe0 sp=0xc21d893fd8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/tim/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7
````

**Comment by syndtr** [comment]
Could you run the program under race detector? See https://golang.org/doc/articles/race_detector.html.

**Comment by karalabe** [comment]
We do that quite often and no issues came up, but this is rather unique to one specific user. Noone else ever experienced or reported it. I'll try asking him to do a race run. Be back with more infos if  can find :)

**Comment by karalabe** [comment]
Closing this as we've never encountered it before :)
