### ISSUE TITLE
Pool drain issue

### ISSUE THREAD

**Issue by ryanstout** [syndtr/goleveldb#123]
First, thanks for the hardwork on goleveldb.  I get the following when my app is idle.  Looks like its from here somehow: https://github.com/syndtr/goleveldb/blob/master/leveldb/util/buffer_pool.go#L237  (Looks like p isn't set)  Any help would be appreciated.  I'm not sure that it matters, but I'm cross compiling to 32bit ARM7 system running SELinux.  Thanks!

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2d0d4]

goroutine 6 [running]:
runtime.gopanic(0x363318, 0x1070a038)
  /home/drobo/xtools/golang/5n/src/runtime/panic.go:425 +0x2a4
runtime.panicmem()
  /home/drobo/xtools/golang/5n/src/runtime/panic.go:42 +0x54
runtime.sigpanic()
  /home/drobo/xtools/golang/5n/src/runtime/sigpanic_unix.go:26 +0x2b0
runtime.timerproc()
  /home/drobo/xtools/golang/5n/src/runtime/time.go:194 +0x304
runtime.goexit()
  /home/drobo/xtools/golang/5n/src/runtime/asm_arm.s:1322 +0x4

goroutine 1 [chan receive, 9 minutes]:
_/gopath/infinitydrive/src/file_watcher.RunWatcher(0x3071c2b8, 0x585764)
  /gopath/infinitydrive/src/file_watcher/file_watcher.go:94 +0xec
main.main()
  /gopath/infinitydrive/src/drive.go:76 +0x310

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10762420)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 14 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x107422a0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 10 [select, 6 minutes]:
net.func·019()
  /home/drobo/xtools/golang/5n/src/net/dnsclient_unix.go:241 +0x310
created by net.loadConfig
  /home/drobo/xtools/golang/5n/src/net/dnsclient_unix.go:269 +0x228

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x107422a0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 16 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x107422a0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 17 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x107422a0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 18 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x107422a0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 19 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x107622c0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 20 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x10742460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 21 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x10742460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 22 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x10742460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 23 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x10742460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 24 [select, 10 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x10742460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 25 [sleep]:
_/gopath/infinitydrive/src/file_reference.func·005()
  /gopath/infinitydrive/src/file_reference/uploader.go:90 +0x46c
created by _/gopath/infinitydrive/src/file_reference.SetupUploader
  /gopath/infinitydrive/src/file_reference/uploader.go:92 +0x2d0

goroutine 26 [chan receive, 6 minutes]:
_/gopath/infinitydrive/src/file_reference.func·006()
  /gopath/infinitydrive/src/file_reference/uploader.go:98 +0x5c
created by _/gopath/infinitydrive/src/file_reference.SetupUploader
  /gopath/infinitydrive/src/file_reference/uploader.go:125 +0x384

goroutine 27 [chan receive, 6 minutes]:
_/gopath/infinitydrive/src/file_reference.func·006()
  /gopath/infinitydrive/src/file_reference/uploader.go:98 +0x5c
created by _/gopath/infinitydrive/src/file_reference.SetupUploader
  /gopath/infinitydrive/src/file_reference/uploader.go:125 +0x384

goroutine 28 [chan receive, 6 minutes]:
_/gopath/infinitydrive/src/file_reference.func·006()
  /gopath/infinitydrive/src/file_reference/uploader.go:98 +0x5c
created by _/gopath/infinitydrive/src/file_reference.SetupUploader
  /gopath/infinitydrive/src/file_reference/uploader.go:125 +0x384

goroutine 29 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10763ad0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 30 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x114e7b20)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 31 [runnable]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x114e7b20)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 32 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x114e7b20)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 33 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x114e7b20)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 34 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x114e7b20)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 35 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10762580)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 36 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x10742a80)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 37 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x10742a80)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 38 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x10742a80)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 39 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x10742a80)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 40 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x10742a80)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 41 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10762790)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 42 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x107435e0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 43 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x107435e0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 44 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x107435e0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 45 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x107435e0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 46 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x107435e0)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 47 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10762840)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 48 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x10743960)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 49 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x10743960)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 50 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x10743960)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 51 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x10743960)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 52 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x10743960)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 53 [sleep]:
_/gopath/infinitydrive/src/file_sync.ProcessSyncQueue()
  /gopath/infinitydrive/src/file_sync/file_sync.go:137 +0x730
created by _/gopath/infinitydrive/src/file_sync.Setup
  /gopath/infinitydrive/src/file_sync/file_sync.go:37 +0x100

goroutine 54 [syscall]:
syscall.Syscall(0x3, 0x1d, 0x12eb7f6c, 0x10000, 0x8, 0x115c99a0, 0xe1e56239)
  /home/drobo/xtools/golang/5n/src/syscall/asm_linux_arm.s:17 +0x8
syscall.read(0x1d, 0x12eb7f6c, 0x10000, 0x10000, 0x0, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/syscall/zsyscall_linux_arm.go:867 +0x80
syscall.Read(0x1d, 0x12eb7f6c, 0x10000, 0x10000, 0x115c1cb4, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/syscall/syscall_unix.go:136 +0x54
_/gopath/infinitydrive/src/fsnotify.(*Watcher).readEvents(0x11559140)
  /gopath/infinitydrive/src/fsnotify/fsnotify_linux.go:230 +0x120
created by _/gopath/infinitydrive/src/fsnotify.NewWatcher
  /gopath/infinitydrive/src/fsnotify/fsnotify_linux.go:137 +0x3f8

goroutine 55 [chan receive]:
_/gopath/infinitydrive/src/fsnotify.(*Watcher).purgeEvents(0x11559140)
  /gopath/infinitydrive/src/fsnotify/fsnotify.go:21 +0x48
created by _/gopath/infinitydrive/src/fsnotify.NewWatcher
  /gopath/infinitydrive/src/fsnotify/fsnotify_linux.go:138 +0x420

goroutine 56 [sleep]:
_/gopath/infinitydrive/src/tasks.run()
  /gopath/infinitydrive/src/tasks/tasks.go:79 +0x194
created by _/gopath/infinitydrive/src/tasks.Setup
  /gopath/infinitydrive/src/tasks/tasks.go:29 +0x34

goroutine 57 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10762a50)
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x220
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
  /golang/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x23c

goroutine 58 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x114e6460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x474
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x794

goroutine 59 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x114e6460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7bc

goroutine 60 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x114e6460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x6a4
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9a4

goroutine 61 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x114e6460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9cc

goroutine 62 [select, 9 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x114e6460)
  /golang/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
  /golang/src/github.com/syndtr/goleveldb/leveldb/db.go:154 +0x9f4

goroutine 63 [sleep]:
_/gopath/infinitydrive/src/archiver.processArchiveQueue()
  /gopath/infinitydrive/src/archiver/archiver.go:132 +0xa4
created by _/gopath/infinitydrive/src/archiver.Setup
  /gopath/infinitydrive/src/archiver/archiver.go:37 +0x1d4

goroutine 64 [select]:
github.com/robfig/go-cache.(*janitor).Run(0x115bb680, 0x115a45a0)
  /golang/src/github.com/robfig/go-cache/cache.go:421 +0x130
created by github.com/robfig/go-cache.runJanitor
  /golang/src/github.com/robfig/go-cache/cache.go:439 +0xb4

goroutine 65 [select]:
github.com/robfig/go-cache.(*janitor).Run(0x115bb690, 0x115a45e0)
  /golang/src/github.com/robfig/go-cache/cache.go:421 +0x130
created by github.com/robfig/go-cache.runJanitor
  /golang/src/github.com/robfig/go-cache/cache.go:439 +0xb4

goroutine 67 [select]:
_/gopath/infinitydrive/src/file_watcher.func·002()
  /gopath/infinitydrive/src/file_watcher/file_watcher.go:40 +0x83c
created by _/gopath/infinitydrive/src/file_watcher.RunWatcher
  /gopath/infinitydrive/src/file_watcher/file_watcher.go:92 +0xcc

goroutine 1529 [IO wait]:
net.(*pollDesc).Wait(0x13e22b78, 0x72, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/net/fd_poll_runtime.go:84 +0x3c
net.(*pollDesc).WaitRead(0x13e22b78, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/net/fd_poll_runtime.go:89 +0x38
net.(*netFD).Read(0x13e22b40, 0x13e50000, 0x1000, 0x1000, 0x0, 0x30715ae8, 0x143b0110)
  /home/drobo/xtools/golang/5n/src/net/fd_unix.go:242 +0x390
net.(*conn).Read(0x123efcc0, 0x13e50000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/net/net.go:121 +0xc8
net/http.noteEOFReader.Read(0x30716fc8, 0x123efcc0, 0x13df570c, 0x13e50000, 0x1000, 0x1000, 0x339b28, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/net/http/transport.go:1270 +0x78
net/http.(*noteEOFReader).Read(0x13e4e160, 0x13e50000, 0x1000, 0x1000, 0x10712000, 0x0, 0x0)
  <autogenerated>:125 +0xec
bufio.(*Reader).fill(0x13e37890)
  /home/drobo/xtools/golang/5n/src/bufio/bufio.go:97 +0x1d8
bufio.(*Reader).Peek(0x13e37890, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
  /home/drobo/xtools/golang/5n/src/bufio/bufio.go:132 +0xd4
net/http.(*persistConn).readLoop(0x13df56e0)
  /home/drobo/xtools/golang/5n/src/net/http/transport.go:842 +0x88
created by net/http.(*Transport).dialConn
  /home/drobo/xtools/golang/5n/src/net/http/transport.go:645 +0xba0

goroutine 1530 [select]:
net/http.(*persistConn).writeLoop(0x13df56e0)
  /home/drobo/xtools/golang/5n/src/net/http/transport.go:945 +0x320
created by net/http.(*Transport).dialConn
  /home/drobo/xtools/golang/5n/src/net/http/transport.go:645 +0xbc8
```

**Comment by syndtr** [comment]
This probably because of this golang/go#8967?

> This is caused by declaring a time.Timer instead of calling a function to create one.
> That's not legal. But we should give a better error, probably make Reset panic or throw.
