### ISSUE TITLE
Closing database while iterating results in a panic instead of an iterator error

### ISSUE THREAD

**Issue by stapelberg** [syndtr/goleveldb#148]
This is my test program:

```go
package main

import (
	"log"
	"time"

	"github.com/syndtr/goleveldb/leveldb"
	"github.com/syndtr/goleveldb/leveldb/opt"
)

func main() {
	db, err := leveldb.OpenFile("/tmp/robustirc-localnet-145995103/irclog", &opt.Options{ErrorIfExist: false})
	if err != nil {
		log.Fatal(err)
	}
	iter := db.NewIterator(nil, nil)
	defer iter.Release()
	go func() {
		var cnt int
		for iter.Next() {
			cnt++
			time.Sleep(5 * time.Millisecond)
		}
		log.Printf("iterated through %d entries\n", cnt)
	}()

	time.Sleep(1 * time.Second)
	db.Close()
	time.Sleep(1 * time.Second)
}
```

When running, I get the following output:
```
panic: runtime error: slice bounds out of range

goroutine 23 [running]:
panic(0x512240, 0xc42000a170)
	/home/michael/go/src/runtime/panic.go:500 +0x1a1
github.com/syndtr/goleveldb/leveldb/table.(*block).entry(0xc42095e700, 0xd4b, 0x1, 0xc420042d80, 0x4ac528, 0xc4200bf230, 0x8, 0x10, 0xc42097c020, 0x8, ...)
	/home/michael/gocode/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:95 +0x433
github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Next(0xc42097a1e0, 0xc420042eb8)
	/home/michael/gocode/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:283 +0x537
github.com/syndtr/goleveldb/leveldb/iterator.(*indexedIterator).Next(0xc42008a1e0, 0xc42002e800)
	/home/michael/gocode/src/github.com/syndtr/goleveldb/leveldb/iterator/indexed_iter.go:149 +0x119
github.com/syndtr/goleveldb/leveldb/iterator.(*mergedIterator).Next(0xc420928180, 0xc42095e880)
	/home/michael/gocode/src/github.com/syndtr/goleveldb/leveldb/iterator/merged_iter.go:169 +0xfc
github.com/syndtr/goleveldb/leveldb.(*dbIter).Next(0xc420016120, 0x1)
	/home/michael/gocode/src/github.com/syndtr/goleveldb/leveldb/db_iter.go:240 +0xa8
main.main.func1(0x5c7400, 0xc420016120)
	/tmp/ldbpoc.go:20 +0x3c
created by main.main
	/tmp/ldbpoc.go:25 +0x11c
exit status 2
```

I would have expected iterator.Next() to return false and iterator.Error() to return an error.

**Comment by syndtr** [comment]
Feel free to reopen this issue if the bug still present. Thanks!
