### ISSUE TITLE
When I put data continuously, panic will happen. panic:still has frozen mem

### ISSUE THREAD

**Issue by aosen** [syndtr/goleveldb#167]
When I put data continuously, panic will happen 

panic: still has frozen mem [recovered]
	panic: still has frozen mem

goroutine 37 [running]:
panic(0x180bc0, 0xc42056d510)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420088240)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x180bc0, 0xc42056d510)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/syndtr/goleveldb/leveldb.(*DB).newMem(0xc42000c480, 0x4d, 0x0, 0x0, 0x0)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_state.go:129 +0x4dc
github.com/syndtr/goleveldb/leveldb.(*DB).rotateMem(0xc42000c480, 0x4d, 0x0, 0xc4200a09a8, 0x0, 0xe696)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:42 +0x66
github.com/syndtr/goleveldb/leveldb.(*DB).flush.func1(0xed0347b00)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:92 +0x2d4
github.com/syndtr/goleveldb/leveldb.(*DB).flush(0xc42000c480, 0x4d, 0xc420a18000, 0x2b, 0x0, 0x0)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:104 +0x175
github.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0xc42000c480, 0xc420565f40, 0xc420565f40, 0x0, 0x0, 0x0)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:141 +0x6c
github.com/syndtr/goleveldb/leveldb.(*DB).putRec(0xc42000c480, 0x1, 0xc420570900, 0x13, 0x20, 0xc42056fc54, 0x32, 0x40, 0x0, 0x58a284c8, ...)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:341 +0x354
github.com/syndtr/goleveldb/leveldb.(*DB).Put(0xc42000c480, 0xc420570900, 0x13, 0x20, 0xc42056fc54, 0x32, 0x40, 0x0, 0x42355, 0xc42056d460)
	/Users/didi/levotao/src/github.com/syndtr/goleveldb/leveldb/db_write.go:351 +0x8d

**Comment by aosen** [comment]
Have to solve this problem，DB address will change，When write buffer reach the threshold.
