### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by PhillippOhlandt** [syndtr/goleveldb#170]
Hey,

I get the following error when I want to open an existing DB:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76e92]

goroutine 1 [running]:
panic(0x1109c0, 0xc42000a090)
       	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(0x0, 0x0)
       	/Users/phillipp/Private/Code/Go/src/github.com/syndtr/goleveldb/leveldb/db_state.go:230 +0x22
github.com/syndtr/goleveldb/leveldb.(*DB).ok(0x0, 0xc42004e070, 0x0)
       	/Users/phillipp/Private/Code/Go/src/github.com/syndtr/goleveldb/leveldb/db_state.go:235 +0x2b
github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0x0, 0x0, 0x0, 0x0)
       	/Users/phillipp/Private/Code/Go/src/github.com/syndtr/goleveldb/leveldb/db.go:876 +0x47
main.main()
       	/Users/phillipp/Private/Code/Go/src/github.com/PhillippOhlandt/leveldb-opener/main.go:13 +0x6b
exit status 2
```

When I use this lib to create a new DB (by specifying a non-existing DB file name), everything works fine. Any ideas?

**Comment by PhillippOhlandt** [comment]
I was told that the DB I want to access is encrypted. That might explain the error.

**Comment by wellzm** [comment]
I had the same problem when I opened an existing database.
