### ISSUE TITLE
Concurently using `batch.put` Causing slice bounds out of range Error 

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [syndtr/goleveldb#289]
when i am concurrently using batch.put method , seems it triggers a error , do i need to use a lock to using this method . 

```
panic: runtime error: slice bounds out of range

goroutine 2925141 [running]:
github.com/elastos/Elastos.ORG.API.Misc/vendor/github.com/syndtr/goleveldb/leveldb.(*Batch).appendRec(0xc00330e000, 0x1, 0xc0003a7b80, 0x19, 0x40, 0xc0046299e0, 0xc4, 0x10a)
	/root/workspace/src/github.com/elastos/Elastos.ORG.API.Misc/vendor/github.com/syndtr/goleveldb/leveldb/batch.go:96 +0x54d
github.com/elastos/Elastos.ORG.API.Misc/vendor/github.com/syndtr/goleveldb/leveldb.(*Batch).Put(...)
	/root/workspace/src/github.com/elastos/Elastos.ORG.API.Misc/vendor/github.com/syndtr/goleveldb/leveldb/batch.go:118
github.com/elastos/Elastos.ORG.API.Misc/chain.handleHeightEth(0x76aafc, 0xc00330e000, 0x300000271, 0x50c0010e90caee8)
	/root/workspace/src/github.com/elastos/Elastos.ORG.API.Misc/chain/eth_sync.go:476 +0x8a9
github.com/elastos/Elastos.ORG.API.Misc/chain.doSyncEth.func1(0xc000025250, 0xc00330e000, 0xc008f385e0, 0xc008f385d0)
	/root/workspace/src/github.com/elastos/Elastos.ORG.API.Misc/chain/eth_sync.go:392 +0x74
created by github.com/elastos/Elastos.ORG.API.Misc/chain.doSyncEth
	/root/workspace/src/github.com/elastos/Elastos.ORG.API.Misc/chain/eth_sync.go:389 +0x34e
```

**Comment by syndtr** [comment]
`Batch` should not be used concurrently. You should either use multiple batch (a dedicated batch per goroutine) or add external synchronization.
