### ISSUE TITLE
Concurrent Write and read creates "invalid memory address or nil pointer dereference" panic

### ISSUE THREAD

**Issue by rajeshell** [syndtr/goleveldb#294]
Hi I am trying to write and read from the same db. which results in Nil pointer dereference panic.
Below are the error messages 

2019/09/16 22:13:14 http: panic serving [::1]:65139: runtime error: invalid memory address or nil pointer dereference
goroutine 31 [running]:
net/http.(*conn).serve.func1(0xc000136000)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x131d000, 0x1625b10)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
        /Users/rajeshloganathan/go/src/github.com/syndtr/goleveldb/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x8, 0xc000042b20)
        /Users/rajeshloganathan/go/src/github.com/syndtr/goleveldb/leveldb/db.go:1127 +0x3f
messdel.Handler(0x13f5dc0, 0xc0001ba2a0, 0xc000130300)
        /Users/rajeshloganathan/go/src/messdel/actions.go:57 +0x95f
net/http.HandlerFunc.ServeHTTP(0x1397538, 0x13f5dc0, 0xc0001ba2a0, 0xc000130300)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1631700, 0x13f5dc0, 0xc0001ba2a0, 0xc000130300)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000be4e0, 0x13f5dc0, 0xc0001ba2a0, 0xc000130300)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000136000, 0x13f6640, 0xc000192580)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
Received List Request:
2019/09/16 22:13:14 http: panic serving [::1]:65178: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc0001360a0)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x131d000, 0x1625b10)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
        /Users/rajeshloganathan/go/src/github.com/syndtr/goleveldb/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x8, 0xc0005b4b20)
        /Users/rajeshloganathan/go/src/github.com/syndtr/goleveldb/leveldb/db.go:1127 +0x3f
messdel.Handler(0x13f5dc0, 0xc0001a8000, 0xc0001ae300)
        /Users/rajeshloganathan/go/src/messdel/actions.go:57 +0x95f
net/http.HandlerFunc.ServeHTTP(0x1397538, 0x13f5dc0, 0xc0001a8000, 0xc0001ae300)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1631700, 0x13f5dc0, 0xc0001a8000, 0xc0001ae300)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000be4e0, 0x13f5dc0, 0xc0001a8000, 0xc0001ae300)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0001360a0, 0x13f6640, 0xc00005b7c0)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by weihaigang** [comment]
Hello, I also encountered such a mistake, do not know how to solve it, my problem is cup first ran to more than 100, then this mistake occurred.

**Comment by weihaigang** [comment]
Hello, I also encountered such a mistake, do not know how to solve it, my problem is cup first ran to more than 100, then this mistake occurred.


`panic: Invalid MessageAuthenticator

goroutine 11 [running]:
main.listenAndServe(0xc000016350, 0xc, 0xc000016390, 0xa, 0xc0000134d0, 0x1, 0x1)
 /home/dou/local/src/radiusd/main.go:35 +0x27b
created by main.main
 /home/dou/local/src/radiusd/main.go:83 +0x441
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x64ae33]

goroutine 21 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db_state.go:230
github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db_state.go:235
github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0xc00007f7a0, 0x0, 0x0, 0x0)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db.go:883 +0x33
radiusd/model.Conns(0xc000016594, 0x4, 0x0, 0x0, 0x1)
 /home/dou/local/src/radiusd/model/model.go:118 +0x100
main.auth(0x869700, 0xc00007f5f0, 0xc00008a280)
 /home/dou/local/src/radiusd/cmd.go:227 +0x329
radiusd/radius.Serve(0xc000010050, 0xc000016390, 0xa, 0xc0000134d0, 0x1, 0x1, 0x1, 0x2)
 /home/dou/local/src/radiusd/radius/Server.go:88 +0x511
main.listenAndServe(0xc000016350, 0xc, 0xc000016390, 0xa, 0xc0000134d0, 0x1, 0x1)
 /home/dou/local/src/radiusd/main.go:29 +0x119
created by main.main
 /home/dou/local/src/radiusd/main.go:83 +0x441
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x64ae33]

goroutine 11 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db_state.go:230
github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db_state.go:235
github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0xc0002fa180, 0x0, 0x0, 0x0)
 /home/dou/local/src/github.com/syndtr/goleveldb/leveldb/db.go:883 +0x33
radiusd/model.Conns(0xc000016648, 0x4, 0x0, 0x0, 0x1)
 /home/dou/local/src/radi`

**Comment by syndtr** [comment]
It looks like you trying to close already closed db or db that never instantiated in the first place.
