### ISSUE TITLE
Slow writes?

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#97]
I was debugging a deadlock in syncthing and ran across this goroutine as the culprit;

```
goroutine 446 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(DB).Write(0xc208024b40, 0xc209806080, 0x0, 0x0, 0x0)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:199 +0x6c3
github.com/syncthing/syncthing/internal/files.ldbGenericReplace(0xc208024b40, 0xc20979e100, 0x6, 0x8, 0xc20ac3e180, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/files/leveldb.go:282 +0x69c
github.com/syncthing/syncthing/internal/files.ldbReplace(0xc208024b40, 0xc20979e100, 0x6, 0x8, 0xc20ac3e180, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/files/leveldb.go:303 +0xa5
github.com/syncthing/syncthing/internal/files.(Set).Replace(0xc208435650, 0x1877f1c42d4a26f2, 0x30dc86619cd860d5, 0x453c5bac58185f49, 0xafe467d59561a164, 0x0, 0x0, 0x0)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/files/set.go:82 +0x2ff
github.com/syncthing/syncthing/internal/model.(Model).Close(0xc2080dd200, 0x1877f1c42d4a26f2, 0x30dc86619cd860d5, 0x453c5bac58185f49, 0xafe467d59561a164, 0x7fd54b4f41b0, 0xc2083993a0)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/model/model.go:621 +0x457
github.com/syncthing/syncthing/internal/protocol.nativeModel.Close(0x7fd5482ca190, 0xc2080dd200, 0x1877f1c42d4a26f2, 0x30dc86619cd860d5, 0x453c5bac58185f49, 0xafe467d59561a164, 0x7fd54b4f41b0, 0xc2083993a0)
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/protocol/nativemodel_unix.go:43 +0x6b
github.com/syncthing/syncthing/internal/protocol.(nativeModel).Close(0xc20979ea40, 0x1877f1c42d4a26f2, 0x30dc86619cd860d5, 0x453c5bac58185f49, 0xafe467d59561a164, 0x7fd54b4f41b0, 0xc2083993a0)
:90 +0xbe
created by github.com/syncthing/syncthing/internal/protocol.func·002
/home/abuild/rpmbuild/BUILD/go/src/github.com/syncthing/syncthing/internal/protocol/protocol.go:567 +0x1c4
```

It holds a lock while doing a bunch of database operations. It looks like the database layer has become stuck ("select, 6 minutes"), or possibly things are going very slowly. From that trace, is that someplace you would expect things to block for minutes, perhaps if the disk isn't super fast?

(The full trace is at the end of https://github.com/syncthing/syncthing/issues/670, not the first one.)

This is on cd2b8f743192883ab9fbc5f070ebda1dc90f3732.

**Comment by icorderi** [comment]
Hey, I just tried using the library. Doing a Put gets stuck (at least for 15 minutes before I terminated the program). 
It first happened on my target linux+ARM, figured it was a cross-compilation issue or something. I get the same behavior on OSX.
